# Render Blueprint for EchoWrite
# This file defines both backend and frontend services for deployment

services:
  # Backend API Service (FastAPI)
  - type: web
    name: echowrite-backend
    runtime: python
    region: oregon
    plan: starter # Free tier available, or starter ($7/mo)
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        generateValue: true # Render provides this
      # These will need to be added manually in Render dashboard:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false # Set this to your frontend URL after frontend is deployed

  # Frontend Service (React + Vite)
  - type: static
    name: echowrite-frontend
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      # This will need to be set after backend is deployed:
      - key: VITE_API_URL
        sync: false # Set to https://echowrite-backend.onrender.com/api/v1

